from building import *
import os

cwd     = GetCurrentDir()
path = [cwd]
src  = []

if GetDepend(['BSP_USING_PID']):
    src += [cwd + '/pid/pid.c']
    path += [cwd + '/pid']

group = DefineGroup('RM_Algorithms', src, depend = [''], CPPPATH = path)

Return('group')
