from building import *
import os

cwd     = GetCurrentDir()

src = [cwd + '/robot.c']

path = [cwd]

if GetDepend(['BSP_USING_EXAMPLE_TASK']):
    src += Glob(cwd + '/example/*.c')
    path += [cwd + '/example']

if GetDepend(['BSP_USING_INS_TASK']):
    src += Glob(cwd + '/ins/*.c')
    path += [cwd + '/ins']

if GetDepend(['BSP_USING_MOTOR_TASK']):
    src += Glob(cwd + '/motor/*.c')
    path += [cwd + '/motor']

group = DefineGroup('RM_Task', src, depend = [''], CPPPATH = path)

Return('group')
